### ISSUE TITLE
Python kódminőség javítás

### ISSUE THREAD

**Issue by vicziani** [iroman2019/homework#2]
* A testName.py gondolom törölhető, vagy ha még majd később akarod használni, nevezd át snake-case-nek megfelelően
* Python-ban tettél bizonyos sorok mögé pontosvesszőt, az nem kell
* operátorok köré space-t szoktunk tenni, azaz a==b helyett a == b
* A PyCharm jobb oldalon sárgával jelzi a konvenciók megsértését (warning) - én azt szoktam mondani, hogy próbáljunk meg csak úgy commit-olni, hogy ne legyen benne sárga

**Comment by iroman2019** [comment]
Ezt javítottam, köszönöm.
